services:
  mysql:
    image: mysql:8.0
    container_name: scheduler_mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  scheduler_service:
    build: ./scheduler_service
    container_name: scheduler_service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    ports:
      - "5000:5000"
    depends_on:
      mysql:
          condition: service_healthy 
  imap_service:
    build: ./imap_service
    container_name: imap_service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    ports:
      - "8000:8000"

volumes:
  mysql_data: